-- Apply after supabase/cosmap_schema.sql

begin;

-- Push token registry
create table if not exists public.push_tokens (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  expo_push_token text not null unique,
  platform text not null default 'unknown',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_push_tokens_profile_id on public.push_tokens (profile_id);

-- Optional queue/log table
create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  target_profile_id uuid not null references public.profiles (id) on delete cascade,
  title text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

-- Admin table for RLS authorization
create table if not exists public.app_admins (
  auth_user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.app_admins a where a.auth_user_id = auth.uid()
  );
$$;

-- RLS enable
alter table public.events enable row level security;
alter table public.event_media enable row level security;
alter table public.push_tokens enable row level security;
alter table public.notification_logs enable row level security;

-- Public read for app
create policy if not exists events_select_all on public.events
for select to anon, authenticated
using (true);

create policy if not exists event_media_select_all on public.event_media
for select to anon, authenticated
using (true);

-- Admin write for events/media
create policy if not exists events_admin_insert on public.events
for insert to authenticated
with check (public.is_admin());

create policy if not exists events_admin_update on public.events
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy if not exists events_admin_delete on public.events
for delete to authenticated
using (public.is_admin());

create policy if not exists event_media_admin_insert on public.event_media
for insert to authenticated
with check (public.is_admin());

create policy if not exists event_media_admin_update on public.event_media
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy if not exists event_media_admin_delete on public.event_media
for delete to authenticated
using (public.is_admin());

-- Push token: owner read/write
create policy if not exists push_tokens_owner_select on public.push_tokens
for select to authenticated
using (
  profile_id in (
    select p.id from public.profiles p where p.auth_user_id = auth.uid()
  )
);

create policy if not exists push_tokens_owner_insert on public.push_tokens
for insert to authenticated
with check (
  profile_id in (
    select p.id from public.profiles p where p.auth_user_id = auth.uid()
  )
);

create policy if not exists push_tokens_owner_update on public.push_tokens
for update to authenticated
using (
  profile_id in (
    select p.id from public.profiles p where p.auth_user_id = auth.uid()
  )
)
with check (
  profile_id in (
    select p.id from public.profiles p where p.auth_user_id = auth.uid()
  )
);

-- Notification log read by owner, insert by admin/function role
create policy if not exists notification_logs_owner_select on public.notification_logs
for select to authenticated
using (
  target_profile_id in (
    select p.id from public.profiles p where p.auth_user_id = auth.uid()
  )
);

create policy if not exists notification_logs_admin_insert on public.notification_logs
for insert to authenticated
with check (public.is_admin());

commit;
